Firma/Controllers/MRebajaController.cs
using Firma.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Firma.Controllers
{
    public class MRebajaController : Controller
    {
        //private ModelMain db = new ModelMain();
        CWRevolutionEntities db = new CWRevolutionEntities();

        // GET: MRebaja
        public ActionResult Index()
        {
            //ViewBag.validate = null;
            return View();
        }

        [HttpPost]
        public ActionResult Index(DateTime finicio, DateTime ffinal, string list, string dgasto, string ccargar)
        {


            ViewBag.validate = 1;
            ViewBag.finicio = finicio;
            ViewBag.ffinal = ffinal;

            ViewBag.list = list;
            ViewBag.dgasto = dgasto;
            ViewBag.ccargar = ccargar;

            decimal total = 0;
            
            var detail = db.SP_Req_MRebaja(finicio, ffinal,list);
            foreach (var item in detail)
            {
                
                item.Costo_Total = decimal.Round(item.Costo_Total, 2);
                total += item.Costo_Total;

            }
            ViewBag.Total = total;
            
            return View(db.SP_Req_MRebaja(finicio, ffinal,list));
            
        }

        public class Header
        {
            public DateTime Finicio { get; set; }
            public DateTime Ffinal { get; set; }
            public string List { get; set; }
            public string Dgasto { get; set; }
            public string Ccargar { get; set; }
            public decimal Total { get; set; }

        }

        public String generarPrimaryKey()
        {
            String res = "";
            int cod = 4000;

            try
            {
                DbQuery<Req_Rebaja_Header> query = db.Set<Req_Rebaja_Header>();
                List<Req_Rebaja_Header> lista = query.ToList();

                // si hay algo en la tabla lo trae extrae el numero y le suma uno
                if (lista.Count() > 0)
                {
                    string codigo = lista.LastOrDefault().Ncons;
                    cod = Convert.ToInt16(codigo.Substring(2));
                    cod = cod + 1;
                }

                // arma el codigo concatenando BR con el numero generado
                res = "BR" + cod;

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return res;
        }



        public ActionResult SaveInfo(Header header)
        {
            try
            {

                var theader = new Req_Rebaja_Header();

                string Ncons = generarPrimaryKey();

                theader.Ncons = Ncons;
                theader.FechaIn = header.Finicio;
                theader.FechaFi = header.Ffinal;
                theader.Departamento = header.List;
                theader.Detalle_Gasto = header.Dgasto;
                theader.Cuenta_Cargar = header.Ccargar;
                theader.Fecha_Rep = DateTime.Now;
                theader.Total = header.Total;

                db.Req_Rebaja_Header.Add(theader);
                Session["Ncons"] = theader.Ncons;


                var detail = db.SP_Req_MRebaja(header.Finicio, header.Ffinal,header.List);
                foreach (var item in detail)
                {
                    var tabla = new Req_Rebaja_Detail();
                    tabla.Ncons = Ncons;
                    tabla.Stringkey = item.Stringkey;
                    tabla.ticket = item.C__de_Ticket.ToString();
                    tabla.Cliente = item.Cliente;
                    tabla.Num_Parte = item.Item_Id;
                    tabla.Descripcion = item.Descripcion_Producto;
                    tabla.Bodega_Rebaja = item.Bodega;
                    tabla.Cant_Solicitada = Convert.ToInt32(item.Cantidad);
                    tabla.Cant_Despachada = item.Quantity_Shipped;
                    tabla.Costo_Unitario = item.Costo_Unitario;
                    tabla.Costo_Total = item.Costo_Total;
                    tabla.Fecha_Shipping = item.Fecha_Shipping;
                    tabla.Hecho_Por = "Admin";
                    tabla.Contrato = item.Contrato;
                    tabla.Proyecto = item.Proyecto;
                    tabla.Bin = item.Bin;
                    

                    db.Req_Rebaja_Detail.Add(tabla);
                }

                db.SaveChanges();
                Descarga();
                
                
                return Json(new { rtn = "Datos guardado" });

            }
            catch (Exception e)
            {

                return Json(new { rtn = e.Message });
            }

        }

        [HttpPost]
        public ActionResult Descarga()
        {
            var ncons = Session["Ncons"];
            System.Diagnostics.Process.Start("http://ptycwclsql/ReportServer_CWISEARIS/Pages/ReportViewer.aspx?%2fCustom%2fREQ_REBAJA_SSRS&rs:Command=Render&Ncons=" + ncons + "&rs:Format=EXCEL");
            

            return View();

        }



    }
}

Firma/Views/MRebaja/Index.cshtml
@model IEnumerable<Firma.SP_Req_MRebaja_Result>
   

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Modulo Rebaja <small>Rebaja de Prodcutos</small></h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                <li class="active">Rebaja</li>
            </ol>
        </div>

    </div><!-- /.row -->

    @if (ViewBag.validate != null)
    {

        <button id="Descarga" class="btn btn-warning" type="button" onclick="Save()">Descargar</button>
        
        <input type="button" class="btn btn-primary" value="Atras" onclick="@("window.location.href='" + @Url.Action("Index", "MRebaja") + "'");" />



        <br>
        <br>

        <table class="table table-bordered table-dark">
            <thead>
                <tr>
                    <th> Ticket </th>
                    <th> Cliente</th>
                    <th width="12%"> Id_Producto </th>
                    <th> Descripcion </th>
                    <th> Dept </th>
                    <th> Cant</th>
                    <th> C/U </th>
                    <th> Total </th>

                    @*<th> Bodega </th>*@
                    <th width="12%">  Bin </th>
                    <th> Contrato </th>

                    @*<th> Quantity_Picked </th>*@

                    <th>Desp</th>
                    <th>  Fecha Shipping  </th>
                    <th>  Proyecto   </th>

                    @*<th> Summary_Ticket </th>
                        <th>  Board  </th>
                        <th>  Configuracion </th>
                        <th>  Numero_Serie </th>
                        <th> Modelo  </th>
                        <th> Oportunidad </th>

                        <th> Fecha_Creacion </th>
                        <th> Fecha_Cierre </th>*@

                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.C__de_Ticket)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cliente)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Item_Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descripcion_Producto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Departamento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cantidad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Costo_Unitario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Costo_Total)
                        </td>
                        @*<td>
                                    @Html.DisplayFor(modelItem => item.Bodega)
                            </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.Bin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Contrato)
                        </td>
                        @*<td>
                                @Html.DisplayFor(modelItem => item.Quantity_Picked)
                            </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity_Shipped)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fecha_Shipping)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Proyecto)
                        </td>
                      
                    </tr>
                }
                <tr>

                    <th colspan="7">TOTAL</th>
                    <th style="text-align: right"> @ViewBag.Total</th>
                    <th colspan="5"></th>


                </tr>
            </tbody>

        </table>




    }
    else
    {

        using (Html.BeginForm("Index", "MRebaja", FormMethod.Post, new { @id = "validate" }))
        {
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="finicio">Fecha Desde</label>
                    <input type="text" id="finicio" class="form-control" name="finicio" readonly>
                </div>
                <div class="form-group col-lg-6">
                    <label for="ffinal">Fecha Hasta</label>
                    <input type="text" id="ffinal" class="form-control" name="ffinal" readonly>
                </div>

                <div class="form-group col-lg-12">
                    <label>Departamento</label>
                    <select class="form-control" id="list" onchange="Dropdown(this)" name="list">
                        <option value="Alta Disponibilidad">Alta Disponibilidad</option>
                        <option value="ATM">ATM</option>
                        <option value="Outsourcing">Contrato de Impresion</option>
                        <option value="Microsistema">Microsistema</option>
                    </select>
                </div>
                <div class="form-group col-lg-12">
                    <label>Detatalle del Gasto</label>
                    <input type="text" class="form-control" id="dgasto" name="dgasto" readonly>
                </div>

                <div class="form-group col-lg-12">
                    <label>Cuenta a Cargar</label>
                    <input type="text" class="form-control" id="ccargar" name="ccargar" readonly>
                </div>

                <script language="javascript">
                    function Dropdown(listSelect) {
                        var val;
                        var val1;

                        switch (listSelect.options[listSelect.selectedIndex].value) {
                            case 'Alta Disponibilidad': val = 'Partes para mantenimiento'
                                val1 = "6245-0800-0080-000"; break;
                            case 'ATM': val = 'Partes para mantenimiento'
                                val1 = " 6255-0800-0080-000"; break;
                            case 'Outsourcing': val = 'Servicio de Impresion Administrada'
                                val1 = "5500-4400-0405-002"; break;
                            case 'Microsistema': val = 'Partes para mantenimiento'
                                val1 = "6225-0800-0080-000"; break;

                        }
                        document.getElementById('dgasto').value = val;
                        document.getElementById('ccargar').value = val1;
                    }

                    Dropdown(document.getElementById('list'));
                </script>


            </div>
            <div class="form-group col-lg-12">

                <button id="submit" type="submit" class="btn btn-success">Buscar</button>

            </div>
        }
    }

</div>


<script type="text/javascript">

    $(function () {
        $('#validate').on('submit', function (event) {
            if ($('#finicio').val() == '' || $('#ffinal').val() == '') {
                alertify.error("Escoja las fechas antes de hacer la busqueda,");
                event.preventDefault();
            }

        });

    })

    $(function () {
        $('#finicio').datepicker({
            autoclose: true,
            format: "yyyy-mm-dd",

        });

    });


    $(function () {
        $('#ffinal').datepicker({
            autoclose: true,
            format: "yyyy-mm-dd",
        });
    });

    

</script>

<script>

    

    function Save() {

        let header={
            finicio: '@ViewBag.finicio',
            ffinal: '@ViewBag.ffinal',
            list: '@ViewBag.list',
            dgasto: '@ViewBag.dgasto',
            ccargar: '@ViewBag.ccargar',
            Total:'@ViewBag.Total'
            
        }

        $.ajax({                     
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: "MRebaja/SaveInfo",
            data: JSON.stringify(header),
            dataType: "json",
            success: function (data) {
                //aqui viene el mensaje
                alertify.success(data.rtn);
                setTimeout(function () {// wait for 5 secs(2)
                    location.reload(); // then reload the page.(3)
                }, 2000);
                             
            },
            error: function (result) {
                console.log(result);
            }
        });

    }
       
</script>